/**
 * Documentation Manifest
 * 
 * Auto-generated file - DO NOT EDIT MANUALLY
 * Generated by: scripts/generate-docs-manifest.js
 * 
 * This manifest contains all available documentation files
 * and their metadata for dynamic menu generation.
 */

export interface DocManifest {
  version: string;
  generated: string;
  sections: DocSection[];
}

export interface DocSection {
  id: string;
  title: string;
  icon: string;
  order: number;
  items: DocItem[];
}

export interface DocItem {
  id: string;
  title: string;
  path: string;
  category: string;
  order: number;
  tags?: string[];
}

// This will be replaced with actual manifest at build time
export const DOCS_MANIFEST: DocManifest = {
  version: '1.0.0',
  generated: new Date().toISOString(),
  sections: [],
};
